version: 0.1

phases:
  install:
    commands:
      - gem install bundler
      - bundle install
  build:
    commands:
      - bundle exec jekyll build
artifacts:
  files:
    - '**/*'
  name: $STATIC_SITE_NAME
  base-directory: _site